INSERT INTO `localization` (`loc_key`, `loc_language`, `loc_val`) VALUES
('ACCOUNT_FORGOT_PASSWORD_EMAIL_BODY_STEP1', 'be', 'Дарагі чалец Wikiarguments,\r\n<br><br>\r\nКалі ласка прайдзіце па гэтай спасылцы, каб запытаць новы пароль: [NEW_PASS_CONFIRM_LINK]\r\n<br><br>\r\nВаша каманда Wikiarguments'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_BODY_STEP2', 'be', 'Дарагі чалец Wikiarguments,\r\n<br><br>\r\nмы стварылі для вас новы пароль. \r\n<br><br>\r\nВаш новы пароль: [PASSWORD]\r\n<br><br>\r\nДля большай бяспекі змяніце свой пароль пасля ўваходу.\r\n<br><br>\r\nВаша каманда Wikiarguments'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_HEADER_STEP1', 'be', 'Забыліся на пароль?'),
('ACCOUNT_FORGOT_PASSWORD_EMAIL_HEADER_STEP2', 'be', 'Ваш новы пароль'),
('ARGUMENT_EDIT', 'be', 'Рэдагаванне (засталося [TIMELEFT] хвілін)'),
('ARGUMENT_EDIT_EXCEEDED', 'be', 'Вы больш не можаце рэдагаваць гэтае абмеркаванне.'),
('CHANGELOG_URL', 'be', '<a href = ''http://en.changelog.wikiarguments.net''>'),
('CHARS_WRITTEN', 'be', 'знакаў напісана'),
('CHARS_WRITTEN_LEFT', 'be', 'знакаў засталося'),
('CHECKIN_CON_CONFIRMED', 'be', 'Голас падлічаны'),
('CHECKIN_PRO_CONFIRMED', 'be', 'Голас падлічаны'),
('COUNTER_ARGUMENT_EDIT_EXCEEDED', 'be', 'Вы больш не можаце рэдагаваць гэтае абмеркаванне.'),
('DIVIDE_USERNAMES', 'be', 'Напішыце імёны карыстальнікаў праз коску'),
('EDIT_QUESTION_HEADLINE', 'be', 'Рэдагаваць Пытанне'),
('ENGLISH', 'be', 'Ангельская'),
('ENGLISH_URL', 'be', '<a href = ''http://en.wikiarguments.net''>'),
('ERROR_COUNTER_ARGUMENT_CHECK_IN_DIFF', 'be', 'Вы не можаце дадаваць контр-аргументы ў сваім раздзеле.'),
('ERROR_COUNTER_ARGUMENT_CHECK_IN_FIRST', 'be', 'Вы павінны ўвайсці, каб ствараць контраргументы.'),
('ERROR_GROUP_INSUFFICIENT_RIGHTS', 'be', 'Недастаткова правоў групы'),
('ERROR_GROUP_NAME_ALREADY_EXISTS', 'be', 'Гэта група ўжо існуе'),
('ERROR_INVALID_ARGUMENT', 'be', 'ERROR_INVALID_ARGUMENT'),
('ERROR_INVALID_FACTION', 'be', 'ERROR_INVALID_FACTION'),
('ERROR_INVALID_GROUP_NAME', 'be', 'Няслушнае імя групы'),
('ERROR_INVALID_PERMISSIONS', 'be', 'Няслушныя правы'),
('ERROR_INVALID_PROFILE', 'be', 'ERROR_INVALID_PROFILE'),
('ERROR_INVALID_QUESTION', 'be', 'Няслушнае пытанне.'),
('ERROR_INVALID_QUESTION_FLAGS', 'be', 'Няслушныя сцягі'),
('ERROR_INVALID_QUESTION_TYPE', 'be', 'Няслушны тып'),
('ERROR_INVALID_VOTE', 'be', 'Няслушны голас.'),
('ERROR_NEW_ARGUMENT_MISSING_ABSTRACT', 'be', 'Калі ласка, стварыце кароткае апісанне.'),
('ERROR_NEW_ARGUMENT_MISSING_DETAILS', 'be', 'ERROR_NEW_ARGUMENT_MISSING_DETAILS'),
('ERROR_NEW_ARGUMENT_MISSING_HEADLINE', 'be', 'Вы мусіце ўвесці загаловак.'),
('ERROR_NEW_ARGUMENT_TRY_AGAIN', 'be', 'Памылка. Калі ласка, паспрабуйце яшчэ раз.'),
('ERROR_NEW_GROUP_TRY_AGAIN', 'be', 'Памылка. Калі ласка, паспрабуйце яшчэ раз.'),
('ERROR_NEW_QUESTION_INVALID_QUESTION', 'be', 'Няслушнае пытанне.'),
('ERROR_NEW_QUESTION_TRY_AGAIN', 'be', 'Памылка. Калі ласка, паспрабуйце яшчэ раз.'),
('ERROR_NOT_CHECKED_IN', 'be', 'Вы павінны ўвесці Так ці Не, каб стварыць абмеркаванні.'),
('ERROR_NOT_LOGGED_IN', 'be', 'Вы павінны ўвайсці, каб ствараць абмеркаванні.'),
('ERROR_NOT_LOGGED_IN_GROUP', 'be', 'Вы павінны ўвайсці, каб стварыць групу.'),
('ERROR_NO_PERMISSION', 'be', 'ERROR_NO_PERMISSION'),
('ERROR_PASS_REQUEST_MISSING_USERNAME', 'be', 'Вы павінны ўвесці сваё імя карыстальніка.'),
('FOOTER_CHANGELOG', 'be', 'Журнал зменаў'),
('FOOTER_COPYRIGHT', 'be', '<a href="/imprint/">Адбітак</a>\r\n'),
('FOOTER_MENU', 'be', 'Меню'),
('FOOTER_NEW_GROUP', 'be', 'Стварыць групу'),
('FOOTER_OPEN_SOURCE', 'be', '<a href="https://code.google.com/p/wikiarguments/">Адчынены Код</a>\r\n'),
('FOOTER_TOS', 'be', '<a href="http://creativecommons.org/licenses/by/3.0/">Змест: CC BY 3.0</a>'),
('GERMAN', 'be', 'Нямецкая'),
('GERMAN_URL', 'be', '<a href = "http://de.wikiarguments.net">de.wikiarguments.net</a>\r\n'),
('GROUPS_URL', 'be', 'en.wikiarguments.net/groups/'),
('GROUP_CHANGE_OWNERSHIP', 'be', 'Уладальнік групы'),
('GROUP_CHANGE_OWNERSHIP_PROMPT', 'be', 'Вы сапраўды хочаце змяніць правы ўладання?'),
('GROUP_CHANGE_OWNERSHIP_SUCCESS', 'be', 'Правы ўладальніка паспяхова перададзены.'),
('GROUP_DELETE_GROUP_PROMPT', 'be', 'Вы сапраўды хочаце выдаліць гэтую групу?'),
('GROUP_DELETE_SUCCESS', 'be', 'Група была паспяхова выдалена.'),
('GROUP_PERMISSION_ADMIN', 'be', 'Адміністратар'),
('GROUP_PERMISSION_ARGUMENTS', 'be', 'Толькі абмеркаванні'),
('GROUP_PERMISSION_OWNER', 'be', 'Уладальнік групы'),
('GROUP_PERMISSION_QUESTIONS', 'be', 'Толькі пытанні'),
('GROUP_PERMISSION_QUESTIONS_ARGUMENTS', 'be', 'Пытанні + Абмеркаванні'),
('GROUP_VISIBILITY', 'be', 'Бачнасць'),
('GROUP_VISIBILITY_PRIVATE', 'be', 'Прыватная'),
('GROUP_VISIBILITY_PUBLIC', 'be', 'Адкрытая'),
('HEADER_NAVI_LOGOUT', 'be', 'Выйсці'),
('HEADER_NAVI_MANAGE_PROFILE', 'be', 'Наладкі'),
('HEADER_NAVI_MY_PROFILE', 'be', 'Мой профіль'),
('HEADER_NAVI_NEW_QUESTION', 'be', 'Новае пытанне'),
('HEADER_NAVI_SHARE_PAGE', 'be', 'Падзяліцца старонкай'),
('HEADER_NEW_GROUP', 'be', 'Новая група'),
('HEADER_SIGNUP', 'be', 'Зарэгістравацца'),
('HTML_HEADER_META_LANG', 'be', 'be'),
('HTML_META_TITLE', 'be', ' - Wikiarguments'),
('HTML_META_TITLE_ARGUMENT', 'be', '[ARGUMENT] - Wikiarguments'),
('HTML_META_TITLE_EDIT_ARGUMENT', 'be', 'Рэдагаваць абмеркаванне'),
('HTML_META_TITLE_EDIT_QUESTION', 'be', 'Рэдагаваць пытанне'),
('HTML_META_TITLE_IMPRINT', 'be', 'Зафіксаваць - Wikiarguments'),
('HTML_META_TITLE_MANAGE_GROUP', 'be', 'Кіраваць групай'),
('HTML_META_TITLE_MANAGE_PROFILE', 'be', 'Змяніць профіль - Wikiarguments'),
('HTML_META_TITLE_NEWEST', 'be', '[TAGS] Новае - Wikiarguments'),
('HTML_META_TITLE_NEW_ARGUMENT', 'be', 'Новае абмеркаванне - Wikiarguments'),
('HTML_META_TITLE_NEW_COUNTER_ARGUMENT', 'be', 'Новы контраргумент - Wikiarguments'),
('HTML_META_TITLE_NEW_GROUP', 'be', 'Новая група'),
('HTML_META_TITLE_NEW_QUESTION', 'be', 'Новае пытанне - Wikiarguments'),
('HTML_META_TITLE_PROFILE', 'be', '[USERNAME] - Wikiarguments'),
('HTML_META_TITLE_QUESTION', 'be', '[QUESTION] - Wikiarguments'),
('HTML_META_TITLE_SIGNUP', 'be', 'Рэгістрацыя - Wikiarguments'),
('HTML_META_TITLE_TOP', 'be', '[TAGS] Топ - Wikiarguments'),
('HTML_META_TITLE_TRENDING', 'be', '[TAGS] Трэнды - Wikiarguments'),
('IMPRINT', 'be', '<div class="headline">Зафіксаваць</div>'),
('LANGUAGE', 'be', 'Мова'),
('LIGHTBOX_CLOSE', 'be', 'Закрыць'),
('LIGHTBOX_PROMPT_NO', 'be', 'Не'),
('LIGHTBOX_PROMPT_YES', 'be', 'Так'),
('LOGIN_ERROR_ACCOUNT_PENDING', 'be', 'Запыт акаўнта'),
('LOGIN_ERROR_ALREADY_LOGGED_IN', 'be', 'Вы ўжо ўвайшлі.'),
('LOGIN_ERROR_INVALID_PASSWORD', 'be', 'Няслушны пароль.'),
('LOGIN_ERROR_INVALID_USERNAME', 'be', 'Няслушнае імя карыстальніка.'),
('LOGIN_FORGOT_PASSWORD', 'be', 'Не памятаю паролю'),
('LOGIN_HEADLINE', 'be', 'Ужо зарэгістраваныя?<br />Уваходзьце тут:'),
('LOGIN_PASSWORD', 'be', 'Пароль'),
('LOGIN_SUBMIT', 'be', 'Лагін'),
('LOGIN_SUCCESS', 'be', 'Вы паспяхова ўвайшлі.'),
('LOGIN_USERNAME', 'be', 'Імя карыстальніка'),
('MANAGE_GROUP_ADD_MEMBERS', 'be', 'Надзяліць правамі'),
('MANAGE_GROUP_GENERAL_INFORMATION', 'be', 'Агульная інфармацыя'),
('MANAGE_GROUP_HEADLINE', 'be', 'Наладкі групы'),
('MANAGE_GROUP_MEMBERS', 'be', 'Карыстальнікі і правы'),
('MANAGE_GROUP_OTHER_SETTINGS', 'be', 'Дадатковыя наладкі'),
('MANAGE_GROUP_OWNER_OPTIONS', 'be', 'Больш опцый'),
('MANAGE_GROUP_URL', 'be', 'URL'),
('MANAGE_HEADLINE', 'be', 'Змяніць пароль'),
('MANAGE_SUBMIT', 'be', 'Захаваць змены'),
('NAVIGATION_NEWEST', 'be', 'Новае'),
('NAVIGATION_SEARCH_DEFAULT', 'be', 'пошук'),
('NAVIGATION_TOP', 'be', 'Toп'),
('NAVIGATION_WHATS_HOT', 'be', 'Трэнды'),
('NEW_ARGUMENT', 'be', 'Дадаць абмеркаванне'),
('NEW_ARGUMENT_ABSTRACT', 'be', 'Абмеркаванне'),
('NEW_ARGUMENT_DETAILS', 'be', 'Дэталі </br>абмеркавання'),
('NEW_ARGUMENT_HEADLINE', 'be', 'Загаловак'),
('NEW_COUNTER_ARGUMENT', 'be', 'Дадаць контраргумент'),
('NEW_GROUP_HEADLINE', 'be', 'Стварыць новую групу'),
('NEW_GROUP_TITLE', 'be', 'Імя'),
('NEW_GROUP_VISIBILITY', 'be', 'Бачнасць'),
('NEW_QUESTION', 'be', 'Новае пытанне'),
('NEW_QUESTION_DETAILS', 'be', 'Падрабязнасці'),
('NEW_QUESTION_FLAGS', 'be', 'Удзел'),
('NEW_QUESTION_HEADLINE', 'be', 'Дадаць новае пытанне'),
('NEW_QUESTION_TAGS', 'be', 'Цэтлікі'),
('NEW_QUESTION_TITLE', 'be', 'Пытанне'),
('NEW_QUESTION_TYPE', 'be', 'Тып'),
('NOTICE_CHECKIN_NOT_LOGGED_IN', 'be', 'Вы павінны ўвайсці.'),
('NOTICE_CONFIRMATION_ERROR_INVALID_USER', 'be', 'NOTICE_CONFIRMATION_ERROR_INVALID_USER'),
('NOTICE_CONFIRMATION_SUCCESS', 'be', 'Вы паспяхова зарэгістраваліся.'),
('NOTICE_NEW_ARGUMENT_NOT_CHECKED_IN', 'be', 'Вы павінны ўвайсці, каб стварыць новае абмеркаванне.'),
('NOTICE_NEW_ARGUMENT_NOT_LOGGED_IN', 'be', 'Вы павінны ўвайсці, каб стварыць новае абмеркаванне.'),
('NOTICE_NEW_ARGUMENT_NO_PERMISSION', 'be', 'NOTICE_NEW_ARGUMENT_NO_PERMISSION'),
('NOTICE_NEW_COUNTER_ARGUMENT_NO_PERMISSION', 'be', 'NOTICE_NEW_COUNTER_ARGUMENT_NO_PERMISSION'),
('NOTICE_NEW_QUESTION_NO_PERMISSION', 'be', 'Недастаткова правоў, каб стварыць пытанне.'),
('NOTICE_NEW_QUESTION_UNLISTED_MANIPULATION', 'be', 'Заўвага: Пунктамі і спісамі вельмі лёгка маніпуляваць.'),
('NOTICE_PASS_REQUEST_SUCCESS', 'be', 'Мы даслалі вам новы пароль на вашу электронную пошту.'),
('NOTICE_VOTE_NOT_CHECKED_IN', 'be', 'Вы павінны быць у фракцыі, каб галасаваць.'),
('NOTICE_VOTE_NOT_LOGGED_IN', 'be', 'Вы павінны ўвайсці, каб галасаваць.'),
('NUM_COUNTER_ARGUMENTS', 'be', 'Контраргументаў'),
('NUM_COUNTER_ARGUMENTS_NULL', 'be', 'Контраргументаў'),
('NUM_COUNTER_ARGUMENTS_ONE', 'be', 'Контраргумент'),
('NUM_COUNTER_ARGUMENTS_TWO', 'be', 'Контраргументы'),
('PAGE_ERROR_INVALID_PAGE', 'be', 'Гэта старонка не існуе.'),
('PAGINATION_PAGE_X_OF_Y', 'be', 'Старонка[CUR] з [MAX]'),
('PARTICIPATION_ALL', 'be', 'Усе'),
('PARTICIPATION_ONLY_REGISTERED', 'be', 'Толькі зарэгістраваныя'),
('PASSWORD_OLD', 'be', 'Стары пароль'),
('PASS_REQUEST_SUCCESS', 'be', 'Мы даслалі вам электронны ліст для абнаўлення паролю.'),
('PROFILE_ARGUMENT_POINTS', 'be', 'Пункты абмеркавання'),
('PROFILE_HEADLINE', 'be', '[USERNAME]'),
('PROFILE_QUESTION_POINTS', 'be', 'Пункты пытання'),
('PROFILE_SIGNUP_DATE', 'be', 'Дата рэгістрацыі: [SIGNUP_DATE]'),
('PROMPT_NO', 'be', 'Не'),
('PROMPT_YES', 'be', 'Так'),
('QUESTION_ARGUMENTS', 'be', '[NUM_ARGUMENTS]'),
('QUESTION_AUTHOR', 'be', 'Дададзена [TIMESINCE] ад [USERNAME]'),
('QUESTION_AUTHOR_ANON', 'be', 'Дададзена [TIMESINCE]'),
('QUESTION_DISTRIBUTION_CON_PERC', 'be', 'Не [PERC]%'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS', 'be', '[NUM] Галасоў'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_NULL', 'be', '[NUM] Галасоў'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_ONE', 'be', '[NUM] Голас'),
('QUESTION_DISTRIBUTION_NUM_CHECKINS_TWO', 'be', '[NUM] Галасы'),
('QUESTION_DISTRIBUTION_PRO_PERC', 'be', 'Так [PERC]%'),
('QUESTION_EDIT', 'be', 'Для рэдагавання застаецца ([TIMELEFT] хвілін)'),
('QUESTION_EDIT_EXCEEDED', 'be', 'Вы больш не можаце рэдагаваць гэтае пытанне.'),
('QUESTION_OPTIONS', 'be', 'Варыянты'),
('QUESTION_POINTS', 'be', 'Пункты'),
('QUESTION_POINTS_NULL', 'be', 'Пунктаў'),
('QUESTION_POINTS_ONE', 'be', 'Пункт'),
('QUESTION_POINTS_TWO', 'be', 'Пункты'),
'QUESTION_TAB_ARGUMENT', 'be', 'A:[TITLE]'),
('QUESTION_TAB_COUNTER_ARGUMENT', 'be', 'КA: [TITLE]'),
('QUESTION_TAB_DETAILS', 'be', 'Падрабязнасці'),
('QUESTION_TAB_DISCUSSION', 'be', 'Дыскусія'),
('QUESTION_TAB_EDIT_ARGUMENT', 'be', 'Рэдагаваць абмеркаванне'),
('QUESTION_TAB_EDIT_COUNTER_ARGUMENT', 'be', 'Рэдагаваць контраргумент'),
('QUESTION_TAB_NEW_ARGUMENT', 'be', 'Новае абмеркаванне'),
('QUESTION_TAB_NEW_COUNTER_ARGUMENT', 'be', 'Новы контраргумент'),
('QUESTION_TYPE_LISTED', 'be', 'У спісе'),
('QUESTION_TYPE_UNLISTED', 'be', 'Не ў спісе'),
('READ_MORE', 'be', 'Чытаць далей >>'),
('REPORT_SPAM', 'be', 'Паскардзіцца на спам'),
('SHARE_FACEBOOK', 'be', 'Facebook'),
('SHARE_TWITTER', 'be', 'Tweet'),
('SIGNUP_CONFIRMATION_EMAIL_BODY', 'be', 'Дарагі (ая)[USERNAME],<br /><br />\r\n\r\n<a href = ''[CONFIRMATION_LINK]''>\r\nНацісніце сюды, каб завяршыць вашу рэгістрацыю на Wikiarguments.</a><br /><br />\r\n\r\nАбо скапіруйце гэтую спасылку ў свой браўзер: [CONFIRMATION_LINK]\r\n<br /><br />\r\nВаша каманда Wikiarguments'),
('SIGNUP_CONFIRMATION_EMAIL_SUBJECT', 'be', 'Рэгістрацыя на Wikiarguments'),
('SIGNUP_EMAIL', 'be', 'Электронная пошта'),
('SIGNUP_ERROR_ALREADY_LOGGED_IN', 'be', 'Вы ўжо ўвайшлі'),
('SIGNUP_ERROR_EMAIL_IN_USE', 'be', 'Гэтая электронная пошта ўжо выкарыстана.'),
('SIGNUP_ERROR_GENERAL', 'be', 'Невядомая памылка.'),
('SIGNUP_ERROR_INVALID_USERNAME', 'be', 'Няслушнае імя карыстальніка'),
('SIGNUP_ERROR_PASSWORD_MISMATCH', 'be', 'Паролі не супадаюць!'),
('SIGNUP_ERROR_USERNAME_EXISTS', 'be', 'Такое імя карыстальніка ўжо існуе.'),
('SIGNUP_HEADLINE', 'be', 'Зарэгістравацца'),
('SIGNUP_PASSWORD', 'be', 'Пароль'),
('SIGNUP_PASSWORD_REPEAT', 'be', 'Паўтарыце пароль'),
('SIGNUP_SUBMIT', 'be', 'Зарэгістравацца'),
('SIGNUP_SUCCESS', 'be', 'Вы атрымалі пацвярджальны электронны ліст. Перайдзіце па ўказанай спасылцы, каб цалкам актывізаваць свой акаўнт.')
('SIGNUP_USERNAME', 'be', 'Імя карыстальніка'),
('SUBMIT_ADD_USERS', 'be', 'Дадаць'),
('SUBMIT_CHANGE_OWNERSHIP', 'be', 'Змяніць уладальніка'),
('SUBMIT_DELETE_GROUP', 'be', 'Выдаліць групу'),
('SUBMIT_NEW_ARGUMENT', 'be', 'Даслаць'),
('SUBMIT_NEW_GROUP', 'be', 'Стварыць групу'),
('SUBMIT_NEW_QUESTION', 'be', 'Даслаць'),
('SUBMIT_OTHER_SETTINGS', 'be', 'Захаваць'),
('SUBMIT_REMOVE_USER', 'be', 'Выдаліць карыстальніка'),
('TAGS_DIVIDE', 'be', 'раздзяліць коскамі |'),
('TAGS_FILTER', 'be', 'Пытанні са словам або цэтлікам "[TAGS]"'),
('TAGS_FILTER_REMOVE', 'be', 'Прыбраць фільтар'),
('TIME_SINCE_DAYS', 'be', '[DAYS] дзён таму'),
('TIME_SINCE_DAYS_NULL', 'be', '[DAYS] дзён таму'),
('TIME_SINCE_DAYS_ONE', 'be', 'адзін дзень таму'),
('TIME_SINCE_DAYS_TWO', 'be', '[DAYS] дні таму'),
('TIME_SINCE_HOURS', 'be', '[HOURS] гадзінаў таму'),
('TIME_SINCE_HOURS_NULL', 'be', '[HOURS] гадзінаў таму'),
('TIME_SINCE_HOURS_ONE', 'be', 'адну гадзіну таму'),
('TIME_SINCE_HOURS_TWO', 'be', '[HOURS] гадзіны таму'),
('TIME_SINCE_MINUTES', 'be', '[MINUTES] хвілінаў таму'),
('TIME_SINCE_MINUTES_NULL', 'be', '[MINUTES] хвілінаў таму'),
('TIME_SINCE_MINUTES_ONE', 'be', 'адну хвіліну таму'),
('TIME_SINCE_MINUTES_TWO', 'be', '[MINUTES] хвіліны таму'),
('TIME_SINCE_MONTHS', 'be', '[MONTHS] месяцаў таму'),
('TIME_SINCE_MONTHS_NULL', 'be', '[MONTHS] месяцаў таму'),
('TIME_SINCE_MONTHS_ONE', 'be', 'адзін месяц таму'),
('TIME_SINCE_MONTHS_TWO', 'be', '[MONTHS] месяцы таму'),
('TIME_SINCE_SECONDS', 'be', '[SECONDS] секундаў таму'),
('TIME_SINCE_SECONDS_NULL', 'be', '[SECONDS] секундаў таму'),
('TIME_SINCE_SECONDS_ONE', 'be', 'адну секунду таму'),
('TIME_SINCE_SECONDS_TWO', 'be', '[SECONDS] секунды таму'),
('TIME_SINCE_YEARS', 'be', '[YEARS] гадоў таму'),
('TIME_SINCE_YEARS_NULL', 'be', '[YEARS] гадоў таму'),
('TIME_SINCE_YEARS_ONE', 'be', 'адзін год таму'),
('TIME_SINCE_YEARS_TWO', 'be', '[YEARS] гады таму'),
('TWITTER_URL', 'be', 'https://twitter.com/WikiargumentsEN'),
('USERNAME_ANON', 'be', 'ананімна');